#include"io.h"

void null_out(uint8_t data){}

uint8_t null_in(void)
{
	return 0;
}

void (*ioOut[256])(uint8_t) =
{
	fileOut,	/*Port 0x0*/
	fileCtl,	/*Port 0x1*/
	null_out,	/*Port 0x2*/
	null_out,	/*Port 0x3*/
	null_out,	/*Port 0x4*/
	null_out,	/*Port 0x5*/
	null_out,	/*Port 0x6*/
	null_out,	/*Port 0x7*/
	null_out,	/*Port 0x8*/
	null_out,	/*Port 0x9*/
	null_out,	/*Port 0xa*/
	null_out,	/*Port 0xb*/
	null_out,	/*Port 0xc*/
	null_out,	/*Port 0xd*/
	null_out,	/*Port 0xe*/
	null_out,	/*Port 0xf*/
	null_out,	/*Port 0x10*/
	null_out,	/*Port 0x11*/
	null_out,	/*Port 0x12*/
	null_out,	/*Port 0x13*/
	null_out,	/*Port 0x14*/
	null_out,	/*Port 0x15*/
	null_out,	/*Port 0x16*/
	null_out,	/*Port 0x17*/
	null_out,	/*Port 0x18*/
	null_out,	/*Port 0x19*/
	null_out,	/*Port 0x1a*/
	null_out,	/*Port 0x1b*/
	null_out,	/*Port 0x1c*/
	null_out,	/*Port 0x1d*/
	null_out,	/*Port 0x1e*/
	null_out,	/*Port 0x1f*/
	null_out,	/*Port 0x20*/
	null_out,	/*Port 0x21*/
	null_out,	/*Port 0x22*/
	null_out,	/*Port 0x23*/
	null_out,	/*Port 0x24*/
	null_out,	/*Port 0x25*/
	null_out,	/*Port 0x26*/
	null_out,	/*Port 0x27*/
	null_out,	/*Port 0x28*/
	null_out,	/*Port 0x29*/
	null_out,	/*Port 0x2a*/
	null_out,	/*Port 0x2b*/
	null_out,	/*Port 0x2c*/
	null_out,	/*Port 0x2d*/
	null_out,	/*Port 0x2e*/
	null_out,	/*Port 0x2f*/
	null_out,	/*Port 0x30*/
	null_out,	/*Port 0x31*/
	null_out,	/*Port 0x32*/
	null_out,	/*Port 0x33*/
	null_out,	/*Port 0x34*/
	null_out,	/*Port 0x35*/
	null_out,	/*Port 0x36*/
	null_out,	/*Port 0x37*/
	null_out,	/*Port 0x38*/
	null_out,	/*Port 0x39*/
	null_out,	/*Port 0x3a*/
	null_out,	/*Port 0x3b*/
	null_out,	/*Port 0x3c*/
	null_out,	/*Port 0x3d*/
	null_out,	/*Port 0x3e*/
	null_out,	/*Port 0x3f*/
	null_out,	/*Port 0x40*/
	null_out,	/*Port 0x41*/
	null_out,	/*Port 0x42*/
	null_out,	/*Port 0x43*/
	null_out,	/*Port 0x44*/
	null_out,	/*Port 0x45*/
	null_out,	/*Port 0x46*/
	null_out,	/*Port 0x47*/
	null_out,	/*Port 0x48*/
	null_out,	/*Port 0x49*/
	null_out,	/*Port 0x4a*/
	null_out,	/*Port 0x4b*/
	null_out,	/*Port 0x4c*/
	null_out,	/*Port 0x4d*/
	null_out,	/*Port 0x4e*/
	null_out,	/*Port 0x4f*/
	null_out,	/*Port 0x50*/
	null_out,	/*Port 0x51*/
	null_out,	/*Port 0x52*/
	null_out,	/*Port 0x53*/
	null_out,	/*Port 0x54*/
	null_out,	/*Port 0x55*/
	null_out,	/*Port 0x56*/
	null_out,	/*Port 0x57*/
	null_out,	/*Port 0x58*/
	null_out,	/*Port 0x59*/
	null_out,	/*Port 0x5a*/
	null_out,	/*Port 0x5b*/
	null_out,	/*Port 0x5c*/
	null_out,	/*Port 0x5d*/
	null_out,	/*Port 0x5e*/
	null_out,	/*Port 0x5f*/
	null_out,	/*Port 0x60*/
	null_out,	/*Port 0x61*/
	null_out,	/*Port 0x62*/
	null_out,	/*Port 0x63*/
	null_out,	/*Port 0x64*/
	null_out,	/*Port 0x65*/
	null_out,	/*Port 0x66*/
	null_out,	/*Port 0x67*/
	null_out,	/*Port 0x68*/
	null_out,	/*Port 0x69*/
	null_out,	/*Port 0x6a*/
	null_out,	/*Port 0x6b*/
	null_out,	/*Port 0x6c*/
	null_out,	/*Port 0x6d*/
	null_out,	/*Port 0x6e*/
	null_out,	/*Port 0x6f*/
	null_out,	/*Port 0x70*/
	null_out,	/*Port 0x71*/
	null_out,	/*Port 0x72*/
	null_out,	/*Port 0x73*/
	null_out,	/*Port 0x74*/
	null_out,	/*Port 0x75*/
	null_out,	/*Port 0x76*/
	null_out,	/*Port 0x77*/
	null_out,	/*Port 0x78*/
	null_out,	/*Port 0x79*/
	null_out,	/*Port 0x7a*/
	null_out,	/*Port 0x7b*/
	null_out,	/*Port 0x7c*/
	null_out,	/*Port 0x7d*/
	null_out,	/*Port 0x7e*/
	null_out,	/*Port 0x7f*/
	null_out,	/*Port 0x80*/
	null_out,	/*Port 0x81*/
	null_out,	/*Port 0x82*/
	null_out,	/*Port 0x83*/
	null_out,	/*Port 0x84*/
	null_out,	/*Port 0x85*/
	null_out,	/*Port 0x86*/
	null_out,	/*Port 0x87*/
	null_out,	/*Port 0x88*/
	null_out,	/*Port 0x89*/
	null_out,	/*Port 0x8a*/
	null_out,	/*Port 0x8b*/
	null_out,	/*Port 0x8c*/
	null_out,	/*Port 0x8d*/
	null_out,	/*Port 0x8e*/
	null_out,	/*Port 0x8f*/
	null_out,	/*Port 0x90*/
	null_out,	/*Port 0x91*/
	null_out,	/*Port 0x92*/
	null_out,	/*Port 0x93*/
	null_out,	/*Port 0x94*/
	null_out,	/*Port 0x95*/
	null_out,	/*Port 0x96*/
	null_out,	/*Port 0x97*/
	null_out,	/*Port 0x98*/
	null_out,	/*Port 0x99*/
	null_out,	/*Port 0x9a*/
	null_out,	/*Port 0x9b*/
	null_out,	/*Port 0x9c*/
	null_out,	/*Port 0x9d*/
	null_out,	/*Port 0x9e*/
	null_out,	/*Port 0x9f*/
	null_out,	/*Port 0xa0*/
	null_out,	/*Port 0xa1*/
	null_out,	/*Port 0xa2*/
	null_out,	/*Port 0xa3*/
	null_out,	/*Port 0xa4*/
	null_out,	/*Port 0xa5*/
	null_out,	/*Port 0xa6*/
	null_out,	/*Port 0xa7*/
	null_out,	/*Port 0xa8*/
	null_out,	/*Port 0xa9*/
	null_out,	/*Port 0xaa*/
	null_out,	/*Port 0xab*/
	null_out,	/*Port 0xac*/
	null_out,	/*Port 0xad*/
	null_out,	/*Port 0xae*/
	null_out,	/*Port 0xaf*/
	null_out,	/*Port 0xb0*/
	null_out,	/*Port 0xb1*/
	null_out,	/*Port 0xb2*/
	null_out,	/*Port 0xb3*/
	null_out,	/*Port 0xb4*/
	null_out,	/*Port 0xb5*/
	null_out,	/*Port 0xb6*/
	null_out,	/*Port 0xb7*/
	null_out,	/*Port 0xb8*/
	null_out,	/*Port 0xb9*/
	null_out,	/*Port 0xba*/
	null_out,	/*Port 0xbb*/
	null_out,	/*Port 0xbc*/
	null_out,	/*Port 0xbd*/
	null_out,	/*Port 0xbe*/
	null_out,	/*Port 0xbf*/
	null_out,	/*Port 0xc0*/
	null_out,	/*Port 0xc1*/
	null_out,	/*Port 0xc2*/
	null_out,	/*Port 0xc3*/
	null_out,	/*Port 0xc4*/
	null_out,	/*Port 0xc5*/
	null_out,	/*Port 0xc6*/
	null_out,	/*Port 0xc7*/
	null_out,	/*Port 0xc8*/
	null_out,	/*Port 0xc9*/
	null_out,	/*Port 0xca*/
	null_out,	/*Port 0xcb*/
	null_out,	/*Port 0xcc*/
	null_out,	/*Port 0xcd*/
	null_out,	/*Port 0xce*/
	null_out,	/*Port 0xcf*/
	null_out,	/*Port 0xd0*/
	null_out,	/*Port 0xd1*/
	null_out,	/*Port 0xd2*/
	null_out,	/*Port 0xd3*/
	null_out,	/*Port 0xd4*/
	null_out,	/*Port 0xd5*/
	null_out,	/*Port 0xd6*/
	null_out,	/*Port 0xd7*/
	null_out,	/*Port 0xd8*/
	null_out,	/*Port 0xd9*/
	null_out,	/*Port 0xda*/
	null_out,	/*Port 0xdb*/
	null_out,	/*Port 0xdc*/
	null_out,	/*Port 0xdd*/
	null_out,	/*Port 0xde*/
	null_out,	/*Port 0xdf*/
	null_out,	/*Port 0xe0*/
	null_out,	/*Port 0xe1*/
	null_out,	/*Port 0xe2*/
	null_out,	/*Port 0xe3*/
	null_out,	/*Port 0xe4*/
	null_out,	/*Port 0xe5*/
	null_out,	/*Port 0xe6*/
	null_out,	/*Port 0xe7*/
	null_out,	/*Port 0xe8*/
	null_out,	/*Port 0xe9*/
	null_out,	/*Port 0xea*/
	null_out,	/*Port 0xeb*/
	null_out,	/*Port 0xec*/
	null_out,	/*Port 0xed*/
	null_out,	/*Port 0xee*/
	null_out,	/*Port 0xef*/
	null_out,	/*Port 0xf0*/
	null_out,	/*Port 0xf1*/
	null_out,	/*Port 0xf2*/
	null_out,	/*Port 0xf3*/
	null_out,	/*Port 0xf4*/
	null_out,	/*Port 0xf5*/
	null_out,	/*Port 0xf6*/
	null_out,	/*Port 0xf7*/
	null_out,	/*Port 0xf8*/
	null_out,	/*Port 0xf9*/
	null_out,	/*Port 0xfa*/
	null_out,	/*Port 0xfb*/
	null_out,	/*Port 0xfc*/
	null_out,	/*Port 0xfd*/
	null_out,	/*Port 0xfe*/
	null_out,	/*Port 0xff*/
};

uint8_t (*ioIn[256])(void) =
{
	fileIn,		/*Port 0x0*/
	fileState,	/*Port 0x1*/
	null_in,	/*Port 0x2*/
	null_in,	/*Port 0x3*/
	null_in,	/*Port 0x4*/
	null_in,	/*Port 0x5*/
	null_in,	/*Port 0x6*/
	null_in,	/*Port 0x7*/
	null_in,	/*Port 0x8*/
	null_in,	/*Port 0x9*/
	null_in,	/*Port 0xa*/
	null_in,	/*Port 0xb*/
	null_in,	/*Port 0xc*/
	null_in,	/*Port 0xd*/
	null_in,	/*Port 0xe*/
	null_in,	/*Port 0xf*/
	null_in,	/*Port 0x10*/
	null_in,	/*Port 0x11*/
	null_in,	/*Port 0x12*/
	null_in,	/*Port 0x13*/
	null_in,	/*Port 0x14*/
	null_in,	/*Port 0x15*/
	null_in,	/*Port 0x16*/
	null_in,	/*Port 0x17*/
	null_in,	/*Port 0x18*/
	null_in,	/*Port 0x19*/
	null_in,	/*Port 0x1a*/
	null_in,	/*Port 0x1b*/
	null_in,	/*Port 0x1c*/
	null_in,	/*Port 0x1d*/
	null_in,	/*Port 0x1e*/
	null_in,	/*Port 0x1f*/
	null_in,	/*Port 0x20*/
	null_in,	/*Port 0x21*/
	null_in,	/*Port 0x22*/
	null_in,	/*Port 0x23*/
	null_in,	/*Port 0x24*/
	null_in,	/*Port 0x25*/
	null_in,	/*Port 0x26*/
	null_in,	/*Port 0x27*/
	null_in,	/*Port 0x28*/
	null_in,	/*Port 0x29*/
	null_in,	/*Port 0x2a*/
	null_in,	/*Port 0x2b*/
	null_in,	/*Port 0x2c*/
	null_in,	/*Port 0x2d*/
	null_in,	/*Port 0x2e*/
	null_in,	/*Port 0x2f*/
	null_in,	/*Port 0x30*/
	null_in,	/*Port 0x31*/
	null_in,	/*Port 0x32*/
	null_in,	/*Port 0x33*/
	null_in,	/*Port 0x34*/
	null_in,	/*Port 0x35*/
	null_in,	/*Port 0x36*/
	null_in,	/*Port 0x37*/
	null_in,	/*Port 0x38*/
	null_in,	/*Port 0x39*/
	null_in,	/*Port 0x3a*/
	null_in,	/*Port 0x3b*/
	null_in,	/*Port 0x3c*/
	null_in,	/*Port 0x3d*/
	null_in,	/*Port 0x3e*/
	null_in,	/*Port 0x3f*/
	null_in,	/*Port 0x40*/
	null_in,	/*Port 0x41*/
	null_in,	/*Port 0x42*/
	null_in,	/*Port 0x43*/
	null_in,	/*Port 0x44*/
	null_in,	/*Port 0x45*/
	null_in,	/*Port 0x46*/
	null_in,	/*Port 0x47*/
	null_in,	/*Port 0x48*/
	null_in,	/*Port 0x49*/
	null_in,	/*Port 0x4a*/
	null_in,	/*Port 0x4b*/
	null_in,	/*Port 0x4c*/
	null_in,	/*Port 0x4d*/
	null_in,	/*Port 0x4e*/
	null_in,	/*Port 0x4f*/
	null_in,	/*Port 0x50*/
	null_in,	/*Port 0x51*/
	null_in,	/*Port 0x52*/
	null_in,	/*Port 0x53*/
	null_in,	/*Port 0x54*/
	null_in,	/*Port 0x55*/
	null_in,	/*Port 0x56*/
	null_in,	/*Port 0x57*/
	null_in,	/*Port 0x58*/
	null_in,	/*Port 0x59*/
	null_in,	/*Port 0x5a*/
	null_in,	/*Port 0x5b*/
	null_in,	/*Port 0x5c*/
	null_in,	/*Port 0x5d*/
	null_in,	/*Port 0x5e*/
	null_in,	/*Port 0x5f*/
	null_in,	/*Port 0x60*/
	null_in,	/*Port 0x61*/
	null_in,	/*Port 0x62*/
	null_in,	/*Port 0x63*/
	null_in,	/*Port 0x64*/
	null_in,	/*Port 0x65*/
	null_in,	/*Port 0x66*/
	null_in,	/*Port 0x67*/
	null_in,	/*Port 0x68*/
	null_in,	/*Port 0x69*/
	null_in,	/*Port 0x6a*/
	null_in,	/*Port 0x6b*/
	null_in,	/*Port 0x6c*/
	null_in,	/*Port 0x6d*/
	null_in,	/*Port 0x6e*/
	null_in,	/*Port 0x6f*/
	null_in,	/*Port 0x70*/
	null_in,	/*Port 0x71*/
	null_in,	/*Port 0x72*/
	null_in,	/*Port 0x73*/
	null_in,	/*Port 0x74*/
	null_in,	/*Port 0x75*/
	null_in,	/*Port 0x76*/
	null_in,	/*Port 0x77*/
	null_in,	/*Port 0x78*/
	null_in,	/*Port 0x79*/
	null_in,	/*Port 0x7a*/
	null_in,	/*Port 0x7b*/
	null_in,	/*Port 0x7c*/
	null_in,	/*Port 0x7d*/
	null_in,	/*Port 0x7e*/
	null_in,	/*Port 0x7f*/
	null_in,	/*Port 0x80*/
	null_in,	/*Port 0x81*/
	null_in,	/*Port 0x82*/
	null_in,	/*Port 0x83*/
	null_in,	/*Port 0x84*/
	null_in,	/*Port 0x85*/
	null_in,	/*Port 0x86*/
	null_in,	/*Port 0x87*/
	null_in,	/*Port 0x88*/
	null_in,	/*Port 0x89*/
	null_in,	/*Port 0x8a*/
	null_in,	/*Port 0x8b*/
	null_in,	/*Port 0x8c*/
	null_in,	/*Port 0x8d*/
	null_in,	/*Port 0x8e*/
	null_in,	/*Port 0x8f*/
	null_in,	/*Port 0x90*/
	null_in,	/*Port 0x91*/
	null_in,	/*Port 0x92*/
	null_in,	/*Port 0x93*/
	null_in,	/*Port 0x94*/
	null_in,	/*Port 0x95*/
	null_in,	/*Port 0x96*/
	null_in,	/*Port 0x97*/
	null_in,	/*Port 0x98*/
	null_in,	/*Port 0x99*/
	null_in,	/*Port 0x9a*/
	null_in,	/*Port 0x9b*/
	null_in,	/*Port 0x9c*/
	null_in,	/*Port 0x9d*/
	null_in,	/*Port 0x9e*/
	null_in,	/*Port 0x9f*/
	null_in,	/*Port 0xa0*/
	null_in,	/*Port 0xa1*/
	null_in,	/*Port 0xa2*/
	null_in,	/*Port 0xa3*/
	null_in,	/*Port 0xa4*/
	null_in,	/*Port 0xa5*/
	null_in,	/*Port 0xa6*/
	null_in,	/*Port 0xa7*/
	null_in,	/*Port 0xa8*/
	null_in,	/*Port 0xa9*/
	null_in,	/*Port 0xaa*/
	null_in,	/*Port 0xab*/
	null_in,	/*Port 0xac*/
	null_in,	/*Port 0xad*/
	null_in,	/*Port 0xae*/
	null_in,	/*Port 0xaf*/
	null_in,	/*Port 0xb0*/
	null_in,	/*Port 0xb1*/
	null_in,	/*Port 0xb2*/
	null_in,	/*Port 0xb3*/
	null_in,	/*Port 0xb4*/
	null_in,	/*Port 0xb5*/
	null_in,	/*Port 0xb6*/
	null_in,	/*Port 0xb7*/
	null_in,	/*Port 0xb8*/
	null_in,	/*Port 0xb9*/
	null_in,	/*Port 0xba*/
	null_in,	/*Port 0xbb*/
	null_in,	/*Port 0xbc*/
	null_in,	/*Port 0xbd*/
	null_in,	/*Port 0xbe*/
	null_in,	/*Port 0xbf*/
	null_in,	/*Port 0xc0*/
	null_in,	/*Port 0xc1*/
	null_in,	/*Port 0xc2*/
	null_in,	/*Port 0xc3*/
	null_in,	/*Port 0xc4*/
	null_in,	/*Port 0xc5*/
	null_in,	/*Port 0xc6*/
	null_in,	/*Port 0xc7*/
	null_in,	/*Port 0xc8*/
	null_in,	/*Port 0xc9*/
	null_in,	/*Port 0xca*/
	null_in,	/*Port 0xcb*/
	null_in,	/*Port 0xcc*/
	null_in,	/*Port 0xcd*/
	null_in,	/*Port 0xce*/
	null_in,	/*Port 0xcf*/
	null_in,	/*Port 0xd0*/
	null_in,	/*Port 0xd1*/
	null_in,	/*Port 0xd2*/
	null_in,	/*Port 0xd3*/
	null_in,	/*Port 0xd4*/
	null_in,	/*Port 0xd5*/
	null_in,	/*Port 0xd6*/
	null_in,	/*Port 0xd7*/
	null_in,	/*Port 0xd8*/
	null_in,	/*Port 0xd9*/
	null_in,	/*Port 0xda*/
	null_in,	/*Port 0xdb*/
	null_in,	/*Port 0xdc*/
	null_in,	/*Port 0xdd*/
	null_in,	/*Port 0xde*/
	null_in,	/*Port 0xdf*/
	null_in,	/*Port 0xe0*/
	null_in,	/*Port 0xe1*/
	null_in,	/*Port 0xe2*/
	null_in,	/*Port 0xe3*/
	null_in,	/*Port 0xe4*/
	null_in,	/*Port 0xe5*/
	null_in,	/*Port 0xe6*/
	null_in,	/*Port 0xe7*/
	null_in,	/*Port 0xe8*/
	null_in,	/*Port 0xe9*/
	null_in,	/*Port 0xea*/
	null_in,	/*Port 0xeb*/
	null_in,	/*Port 0xec*/
	null_in,	/*Port 0xed*/
	null_in,	/*Port 0xee*/
	null_in,	/*Port 0xef*/
	null_in,	/*Port 0xf0*/
	null_in,	/*Port 0xf1*/
	null_in,	/*Port 0xf2*/
	null_in,	/*Port 0xf3*/
	null_in,	/*Port 0xf4*/
	null_in,	/*Port 0xf5*/
	null_in,	/*Port 0xf6*/
	null_in,	/*Port 0xf7*/
	null_in,	/*Port 0xf8*/
	null_in,	/*Port 0xf9*/
	null_in,	/*Port 0xfa*/
	null_in,	/*Port 0xfb*/
	null_in,	/*Port 0xfc*/
	null_in,	/*Port 0xfd*/
	null_in,	/*Port 0xfe*/
	null_in,	/*Port 0xff*/
};

uint8_t input(uint8_t port)
{
	return ioIn[port]();
}

void output(uint8_t port, uint8_t data)
{
	ioOut[port](data);
}
